version: "3"
services:
  nacos1:
    container_name: nacos-server01
    hostname: nacos-server01
    image: nacos/nacos-server:${NACOS_VERSION}
    restart: always
    ports:
      - 8845:8848
      - 9845:9848
      - 9841:9849
    environment:
      - MODE=${NACOS_MODE}
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=${NACOS_SPRING_DATASOURCE_PLATFORM}
      - MYSQL_SERVICE_HOST=${NACOS_MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${NACOS_MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${NACOS_MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${NACOS_MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_NAME=${NACOS_MYSQL_SERVICE_DB_NAME}
      - JVM_XMS=128m
      - JVM_XMX=512m
      - JVM_XMN=128m
    volumes:
      - ${LOG_DIR}/nacos1:/home/nacos/logs:rw
      - ${NACOS_CLUSTER_DIR}/nacos1/custom.properties:/home/nacos/init.d/custom.properties:rw


  nacos2:
    container_name: nacos-server02
    hostname: nacos-server02
    image: nacos/nacos-server:${NACOS_VERSION}
    restart: always
    ports:
      - 8846:8848
      - 9846:9848
      - 9842:9849
    environment:
      - MODE=${NACOS_MODE}
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=${NACOS_SPRING_DATASOURCE_PLATFORM}
      - MYSQL_SERVICE_HOST=${NACOS_MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${NACOS_MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${NACOS_MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${NACOS_MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_NAME=${NACOS_MYSQL_SERVICE_DB_NAME}
      - JVM_XMS=128m
      - JVM_XMX=512m
      - JVM_XMN=128m
    volumes:
      - ${LOG_DIR}/nacos2:/home/nacos/logs:rw
      - ${NACOS_CLUSTER_DIR}/nacos2/custom.properties:/home/nacos/init.d/custom.properties:rw

  nacos3:
    container_name: nacos-server03
    hostname: nacos-server03
    image: nacos/nacos-server:${NACOS_VERSION}
    restart: always
    ports:
      - 8847:8848
      - 9847:9848
      - 9843:9849
    environment:
      - MODE=${NACOS_MODE}
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=${NACOS_SPRING_DATASOURCE_PLATFORM}
      - MYSQL_SERVICE_HOST=${NACOS_MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${NACOS_MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${NACOS_MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${NACOS_MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_NAME=${NACOS_MYSQL_SERVICE_DB_NAME}
      - JVM_XMS=128m
      - JVM_XMX=512m
      - JVM_XMN=128m
    volumes:
      - ${LOG_DIR}/nacos3:/home/nacos/logs:rw
      - ${NACOS_CLUSTER_DIR}/nacos3/custom.properties:/home/nacos/init.d/custom.properties:rw


  nacos-nginx:
    container_name: nacos-nginx
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    volumes:
      - ${NGINX_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_DIR}/conf:/etc/nginx/conf.d:rw
      - ${LOG_DIR}/nginx:/var/log/nginx:rw
